import React from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>GUESS THE POKEMON</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/pokemon.ico" />
			</Head>

			<header className={styles.title}>
				<h1>Guess The Pokemon</h1>
			</header>
		</div>
	);
}
